services:
  - type: web
    name: cirlo-waitlist
    runtime: node
    plan: free
    buildCommand: "npm install && npm run build && cd backend && npm install"
    startCommand: "node backend/index.js"
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
